export enum ActivityType {
    CREATE_BOARD = 1,
    UPDATE_BOARD = 2,
    DELETE_BOARD = 3,
    CREATE_CARD = 4,
    UPDATE_CARD = 5,
    DELETE_CARD = 6,
    CREATE_LIST = 7,
    UPDATE_LIST = 8,
    DELETE_LIST = 9,
    MOVE_CARD = 10,
    ARCHIVE_LIST = 11,
    UNARCHIVE_LIST = 12,
    ARCHIVE_CARD = 13,
    UNARCHIVE_CARD = 14,

}